apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: web-prod
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-prod
  name: web-prod
  namespace: web-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-prod
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
