apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-prod
  name: web-prod
  namespace: web-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-prod
  template:
    metadata:
      labels:
        app: web-prod
    spec:
      containers:
      - image: nginx
        name: nginx
